/**
 *
 *  Collections.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Collections.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Mnemosyne;

const std::string Collections::Cols::_id = "id";
const std::string Collections::Cols::_name = "name";
const std::string Collections::Cols::_audios = "audios";
const std::string Collections::Cols::_documents = "documents";
const std::string Collections::Cols::_ebooks = "ebooks";
const std::string Collections::Cols::_images = "images";
const std::string Collections::Cols::_models = "models";
const std::string Collections::Cols::_videos = "videos";
const std::string Collections::primaryKeyName = "id";
const bool Collections::hasPrimaryKey = true;
const std::string Collections::tableName = "collections";

const std::vector<typename Collections::MetaData> Collections::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"name","std::string","text",0,0,0,0},
{"audios","std::string","text",0,0,0,0},
{"documents","std::string","text",0,0,0,0},
{"ebooks","std::string","text",0,0,0,0},
{"images","std::string","text",0,0,0,0},
{"models","std::string","text",0,0,0,0},
{"videos","std::string","text",0,0,0,0}
};
const std::string &Collections::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Collections::Collections(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["audios"].isNull())
        {
            audios_=std::make_shared<std::string>(r["audios"].as<std::string>());
        }
        if(!r["documents"].isNull())
        {
            documents_=std::make_shared<std::string>(r["documents"].as<std::string>());
        }
        if(!r["ebooks"].isNull())
        {
            ebooks_=std::make_shared<std::string>(r["ebooks"].as<std::string>());
        }
        if(!r["images"].isNull())
        {
            images_=std::make_shared<std::string>(r["images"].as<std::string>());
        }
        if(!r["models"].isNull())
        {
            models_=std::make_shared<std::string>(r["models"].as<std::string>());
        }
        if(!r["videos"].isNull())
        {
            videos_=std::make_shared<std::string>(r["videos"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            audios_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            documents_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            ebooks_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            images_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            models_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            videos_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Collections::Collections(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            audios_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            documents_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            ebooks_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            images_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            models_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            videos_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

Collections::Collections(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("audios"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["audios"].isNull())
        {
            audios_=std::make_shared<std::string>(pJson["audios"].asString());
        }
    }
    if(pJson.isMember("documents"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["documents"].isNull())
        {
            documents_=std::make_shared<std::string>(pJson["documents"].asString());
        }
    }
    if(pJson.isMember("ebooks"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["ebooks"].isNull())
        {
            ebooks_=std::make_shared<std::string>(pJson["ebooks"].asString());
        }
    }
    if(pJson.isMember("images"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["images"].isNull())
        {
            images_=std::make_shared<std::string>(pJson["images"].asString());
        }
    }
    if(pJson.isMember("models"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["models"].isNull())
        {
            models_=std::make_shared<std::string>(pJson["models"].asString());
        }
    }
    if(pJson.isMember("videos"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["videos"].isNull())
        {
            videos_=std::make_shared<std::string>(pJson["videos"].asString());
        }
    }
}

void Collections::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            audios_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            documents_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            ebooks_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            images_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            models_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            videos_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

void Collections::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("audios"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["audios"].isNull())
        {
            audios_=std::make_shared<std::string>(pJson["audios"].asString());
        }
    }
    if(pJson.isMember("documents"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["documents"].isNull())
        {
            documents_=std::make_shared<std::string>(pJson["documents"].asString());
        }
    }
    if(pJson.isMember("ebooks"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["ebooks"].isNull())
        {
            ebooks_=std::make_shared<std::string>(pJson["ebooks"].asString());
        }
    }
    if(pJson.isMember("images"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["images"].isNull())
        {
            images_=std::make_shared<std::string>(pJson["images"].asString());
        }
    }
    if(pJson.isMember("models"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["models"].isNull())
        {
            models_=std::make_shared<std::string>(pJson["models"].asString());
        }
    }
    if(pJson.isMember("videos"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["videos"].isNull())
        {
            videos_=std::make_shared<std::string>(pJson["videos"].asString());
        }
    }
}

const int32_t &Collections::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Collections::getId() const noexcept
{
    return id_;
}
void Collections::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Collections::PrimaryKeyType & Collections::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Collections::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getName() const noexcept
{
    return name_;
}
void Collections::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Collections::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}
void Collections::setNameToNull() noexcept
{
    name_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Collections::getValueOfAudios() const noexcept
{
    const static std::string defaultValue = std::string();
    if(audios_)
        return *audios_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getAudios() const noexcept
{
    return audios_;
}
void Collections::setAudios(const std::string &pAudios) noexcept
{
    audios_ = std::make_shared<std::string>(pAudios);
    dirtyFlag_[2] = true;
}
void Collections::setAudios(std::string &&pAudios) noexcept
{
    audios_ = std::make_shared<std::string>(std::move(pAudios));
    dirtyFlag_[2] = true;
}
void Collections::setAudiosToNull() noexcept
{
    audios_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Collections::getValueOfDocuments() const noexcept
{
    const static std::string defaultValue = std::string();
    if(documents_)
        return *documents_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getDocuments() const noexcept
{
    return documents_;
}
void Collections::setDocuments(const std::string &pDocuments) noexcept
{
    documents_ = std::make_shared<std::string>(pDocuments);
    dirtyFlag_[3] = true;
}
void Collections::setDocuments(std::string &&pDocuments) noexcept
{
    documents_ = std::make_shared<std::string>(std::move(pDocuments));
    dirtyFlag_[3] = true;
}
void Collections::setDocumentsToNull() noexcept
{
    documents_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Collections::getValueOfEbooks() const noexcept
{
    const static std::string defaultValue = std::string();
    if(ebooks_)
        return *ebooks_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getEbooks() const noexcept
{
    return ebooks_;
}
void Collections::setEbooks(const std::string &pEbooks) noexcept
{
    ebooks_ = std::make_shared<std::string>(pEbooks);
    dirtyFlag_[4] = true;
}
void Collections::setEbooks(std::string &&pEbooks) noexcept
{
    ebooks_ = std::make_shared<std::string>(std::move(pEbooks));
    dirtyFlag_[4] = true;
}
void Collections::setEbooksToNull() noexcept
{
    ebooks_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Collections::getValueOfImages() const noexcept
{
    const static std::string defaultValue = std::string();
    if(images_)
        return *images_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getImages() const noexcept
{
    return images_;
}
void Collections::setImages(const std::string &pImages) noexcept
{
    images_ = std::make_shared<std::string>(pImages);
    dirtyFlag_[5] = true;
}
void Collections::setImages(std::string &&pImages) noexcept
{
    images_ = std::make_shared<std::string>(std::move(pImages));
    dirtyFlag_[5] = true;
}
void Collections::setImagesToNull() noexcept
{
    images_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Collections::getValueOfModels() const noexcept
{
    const static std::string defaultValue = std::string();
    if(models_)
        return *models_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getModels() const noexcept
{
    return models_;
}
void Collections::setModels(const std::string &pModels) noexcept
{
    models_ = std::make_shared<std::string>(pModels);
    dirtyFlag_[6] = true;
}
void Collections::setModels(std::string &&pModels) noexcept
{
    models_ = std::make_shared<std::string>(std::move(pModels));
    dirtyFlag_[6] = true;
}
void Collections::setModelsToNull() noexcept
{
    models_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Collections::getValueOfVideos() const noexcept
{
    const static std::string defaultValue = std::string();
    if(videos_)
        return *videos_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Collections::getVideos() const noexcept
{
    return videos_;
}
void Collections::setVideos(const std::string &pVideos) noexcept
{
    videos_ = std::make_shared<std::string>(pVideos);
    dirtyFlag_[7] = true;
}
void Collections::setVideos(std::string &&pVideos) noexcept
{
    videos_ = std::make_shared<std::string>(std::move(pVideos));
    dirtyFlag_[7] = true;
}
void Collections::setVideosToNull() noexcept
{
    videos_.reset();
    dirtyFlag_[7] = true;
}

void Collections::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Collections::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "name",
        "audios",
        "documents",
        "ebooks",
        "images",
        "models",
        "videos"
    };
    return inCols;
}

void Collections::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAudios())
        {
            binder << getValueOfAudios();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDocuments())
        {
            binder << getValueOfDocuments();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEbooks())
        {
            binder << getValueOfEbooks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImages())
        {
            binder << getValueOfImages();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModels())
        {
            binder << getValueOfModels();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getVideos())
        {
            binder << getValueOfVideos();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Collections::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Collections::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAudios())
        {
            binder << getValueOfAudios();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDocuments())
        {
            binder << getValueOfDocuments();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEbooks())
        {
            binder << getValueOfEbooks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImages())
        {
            binder << getValueOfImages();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModels())
        {
            binder << getValueOfModels();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getVideos())
        {
            binder << getValueOfVideos();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Collections::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getAudios())
    {
        ret["audios"]=getValueOfAudios();
    }
    else
    {
        ret["audios"]=Json::Value();
    }
    if(getDocuments())
    {
        ret["documents"]=getValueOfDocuments();
    }
    else
    {
        ret["documents"]=Json::Value();
    }
    if(getEbooks())
    {
        ret["ebooks"]=getValueOfEbooks();
    }
    else
    {
        ret["ebooks"]=Json::Value();
    }
    if(getImages())
    {
        ret["images"]=getValueOfImages();
    }
    else
    {
        ret["images"]=Json::Value();
    }
    if(getModels())
    {
        ret["models"]=getValueOfModels();
    }
    else
    {
        ret["models"]=Json::Value();
    }
    if(getVideos())
    {
        ret["videos"]=getValueOfVideos();
    }
    else
    {
        ret["videos"]=Json::Value();
    }
    return ret;
}

Json::Value Collections::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAudios())
            {
                ret[pMasqueradingVector[2]]=getValueOfAudios();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDocuments())
            {
                ret[pMasqueradingVector[3]]=getValueOfDocuments();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEbooks())
            {
                ret[pMasqueradingVector[4]]=getValueOfEbooks();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getImages())
            {
                ret[pMasqueradingVector[5]]=getValueOfImages();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getModels())
            {
                ret[pMasqueradingVector[6]]=getValueOfModels();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getVideos())
            {
                ret[pMasqueradingVector[7]]=getValueOfVideos();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getAudios())
    {
        ret["audios"]=getValueOfAudios();
    }
    else
    {
        ret["audios"]=Json::Value();
    }
    if(getDocuments())
    {
        ret["documents"]=getValueOfDocuments();
    }
    else
    {
        ret["documents"]=Json::Value();
    }
    if(getEbooks())
    {
        ret["ebooks"]=getValueOfEbooks();
    }
    else
    {
        ret["ebooks"]=Json::Value();
    }
    if(getImages())
    {
        ret["images"]=getValueOfImages();
    }
    else
    {
        ret["images"]=Json::Value();
    }
    if(getModels())
    {
        ret["models"]=getValueOfModels();
    }
    else
    {
        ret["models"]=Json::Value();
    }
    if(getVideos())
    {
        ret["videos"]=getValueOfVideos();
    }
    else
    {
        ret["videos"]=Json::Value();
    }
    return ret;
}

bool Collections::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    if(pJson.isMember("audios"))
    {
        if(!validJsonOfField(2, "audios", pJson["audios"], err, true))
            return false;
    }
    if(pJson.isMember("documents"))
    {
        if(!validJsonOfField(3, "documents", pJson["documents"], err, true))
            return false;
    }
    if(pJson.isMember("ebooks"))
    {
        if(!validJsonOfField(4, "ebooks", pJson["ebooks"], err, true))
            return false;
    }
    if(pJson.isMember("images"))
    {
        if(!validJsonOfField(5, "images", pJson["images"], err, true))
            return false;
    }
    if(pJson.isMember("models"))
    {
        if(!validJsonOfField(6, "models", pJson["models"], err, true))
            return false;
    }
    if(pJson.isMember("videos"))
    {
        if(!validJsonOfField(7, "videos", pJson["videos"], err, true))
            return false;
    }
    return true;
}
bool Collections::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Collections::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("audios"))
    {
        if(!validJsonOfField(2, "audios", pJson["audios"], err, false))
            return false;
    }
    if(pJson.isMember("documents"))
    {
        if(!validJsonOfField(3, "documents", pJson["documents"], err, false))
            return false;
    }
    if(pJson.isMember("ebooks"))
    {
        if(!validJsonOfField(4, "ebooks", pJson["ebooks"], err, false))
            return false;
    }
    if(pJson.isMember("images"))
    {
        if(!validJsonOfField(5, "images", pJson["images"], err, false))
            return false;
    }
    if(pJson.isMember("models"))
    {
        if(!validJsonOfField(6, "models", pJson["models"], err, false))
            return false;
    }
    if(pJson.isMember("videos"))
    {
        if(!validJsonOfField(7, "videos", pJson["videos"], err, false))
            return false;
    }
    return true;
}
bool Collections::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Collections::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
